version: "3"
services:
    chat_app_instancer:
        build: .
        ports:
            - 9000:9000
            - 7002-7006:7002-7006
        privileged: true
        environment:
            - "INSTANCER_DEBUG=1"