[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.23.0", features = ["all-widgets"] }
crossterm = "0.26"
itertools = "0.11.0"
chat_common = { path = "../common" }
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread"] }
rand = "0.8.5"
chrono = "0.4.31"