[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chat_common = { path = "../common" }
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread"] }